[package]
name = "rustifzm"
version = "0.0.1"
authors = ["pierreyoda <pierreyoda@users.noreply.github.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
thiserror = "1.0.29"
bitflags = "1.3.2"
